src/Entity/Author.php
<?php

namespace App\Entity;

use App\Repository\AuthorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AuthorRepository::class)]
class Author
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Biographie = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $Image = null;

    #[ORM\OneToMany(targetEntity: Livre::class, mappedBy: 'author')]
    private Collection $livres;

    #[ORM\Column(length: 100)]
    private ?string $firstname = null;

    #[ORM\Column(length: 100)]
    private ?string $lastname = null;

    #[ORM\ManyToOne(inversedBy: 'authors')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    public function __construct()
    {
        $this->livres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }
    public function __toString()
    {
        $format = "author(firstname:%s, image:%,)\n";
        return sprintf($this->firstname, $this->lastname, $this->Image);
    }
    public function getBiographie(): ?string
    {
        return $this->Biographie;
    }

    public function setBiographie(string $Biographie): static
    {
        $this->Biographie = $Biographie;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(?string $Image): static
    {
        $this->Image = $Image;

        return $this;
    }

    /**
     * @return Collection<int, Livre>
     */
    public function getLivres(): Collection
    {
        return $this->livres;
    }

    public function addLivre(Livre $livre): static
    {
        if (!$this->livres->contains($livre)) {
            $this->livres->add($livre);
            $livre->setAuthor($this);
        }

        return $this;
    }

    public function removeLivre(Livre $livre): static
    {
        if ($this->livres->removeElement($livre)) {
            // set the owning side to null (unless already changed)
            if ($livre->getAuthor() === $this) {
                $livre->setAuthor(null);
            }
        }

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

}

src/Entity/Livre.php
<?php

namespace App\Entity;

use App\Repository\LivreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[Vich\Uploadable]
#[ORM\Entity(repositoryClass: LivreRepository::class)]
class Livre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Abstract = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Content = null;

    #[ORM\ManyToOne(inversedBy: 'livres')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Genre $genre = null;

    #[ORM\ManyToOne(inversedBy: 'livres')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'livres')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Author $author = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;


    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[Gedmo\Slug(fields:['title'])]
    #[ORM\Column(length: 128)]
    private ?string $slug = null;

    #[ORM\OneToMany(targetEntity: Comment::class, mappedBy: 'livre')]
    private Collection $comments;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable('now');
        $this->comments = new ArrayCollection();
    }
    public function getAbstract(): ?string
    {
        return $this->Abstract;
    }

    public function setAbstract(string $Abstract): static
    {
        $this->Abstract = $Abstract;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(string $Content): static
    {
        $this->Content = $Content;

        return $this;
    }

    public function getGenre(): ?Genre
    {
        return $this->genre;
    }

    public function setGenre(?Genre $genre): static
    {
        $this->genre = $genre;

        return $this;
    }


    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getAuthor(): ?Author
    {
        return $this->author;
    }

    public function setAuthor(?Author $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    /*public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }*/

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setLivre($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getLivre() === $this) {
                $comment->setLivre(null);
            }
        }

        return $this;
    }


}

templates/show/livres.html.twig
{% extends 'base.html.twig' %}
{% block title %}Livres{% endblock %}
{% block body %}
<div class="container-fluid mb-5">
    <div class="container">
        <div class="col-md-12 mt-5">
            <div class"row">
                {% for livres in livres %}
                    <div class="col-md-12 mb-2 "><a class="h2-livre" href="{{path('livres', {'id' :livres.id}) }}">{{livres.title}}</a></div>
                    <div class="col-md-12 mb-2 "><a class="h2-livre" href="{{path('livres', {'id' :livres.id}) }}">{{livres.author.firstname}}&nbsp{{livres.author.lastname}}</a></div>

                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/show/readOne.html.twig
{% extends 'base.html.twig' %}
{% block title %}ReadOne{% endblock %}
{% block body %}
<div class="container-fluid mb-5">
    <div class="container">
    <div class="col-md-12 mt-5">
        <div class"row">
            <div class="col-md-8">
                <div class="col-md-12 mb-5 h2-page-livre">{{livre.title}}</div>
                <div class="col-md-12 mb-5">{{livre.author.firstname}}&nbsp;{{livre.author.lastname}}</div>
            </div>

            <div class="col-md-4 mb-5"><img class="img-fluid" src="{{asset('divers/images/livres/' ~ livre.image)}}" alt=""></div>
        </div>
    </div>
        <div class="col-md-12 mb-5">{{livre.content|nl2br}}</div>
        {#Appel du formulaire#}
        <div class="row mb-3">
            {% include "comment/comment.html.twig" with{'parentcommentForm' : commentForm} %}
        </div>
        <div class="row mb-5">
            <p>
                <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                    Affichez <span><script id="nombrecomments"></script></span> commentaires
                </button>
            </p>
            <div class="collapse" id="collapseExample comments">
                {% for comment in comments %}
                    <div class="col-md-1 mb-0">
                        <img class="img-fluid" src="{{asset('divers/images/users/' ~ comment.user.avatar)}}" alt="avatar"> 
                    </div>
                    <div class="col-md-11 mb-4">
                        <div class="row">
                            <div class="col-md-12">
                                <span class="zhcdina">{{comment.user.firstname}} &nbsp; {{comment.user.lastname}}</span> &ensp;
                                <span class="zrddate">{{ comment.createdAt|date('D d M Y H:i') }}</span> 
                            </div>
                            <div class="col-md-12 zhccontent">{{ comment.content|striptags|nl2br }}</div>
                         </div>
                    </div>
                {% endfor %}
            </div>
        </div>
</div>
{% endblock %}

templates/show/readOneAuthor.html.twig
{% extends 'base.html.twig' %}
{% block title %}ReadOneAuthor{% endblock %}
{% block body %}
<div class="container-fluid mb-5 h-80">
    <div class="container">
    <div class="col-md-12 mt-5">
        <div class"row">
            <div class="col-md-12">
                <div class="row">
                <div class="col-md-4">
                    <div class="col-md-2 mb-5 h2-page-livre">{{ author.firstname }}</div>
                    <div class="col-md-2 mb-5 h2-page-livre">{{ author.lastname }}</div>
                </div>
                    <div class="col-md-8 mb-5"><img class="img-fluid" src="{{asset('divers/images/' ~ author.image)}}" alt=""></div>
                </div>    
            </div>
            
        </div>
    </div>
        <div class="col-md-12 mb-5">{{ author.biographie|nl2br }}</div>
    </div>
</div>
{% endblock %}

templates/show/readOneGenre.html.twig
{% extends 'base.html.twig' %}
{% block title %}ReadOneGenre{% endblock %}
{% block body %}
<div class="container-fluid mb-5">
    <div class="container">
    <div class="col-md-12 mt-5">
        <div class"row">
            <div class="col-md-12">

                    {{ genre.name }}
                        
            </div>
            
        </div>
    </div>
        {#<div class="col-md-12 mb-5">{{  }}</div>#}
    </div>
</div>
{% endblock %}